In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%config InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
data = np.array([[1, 2, 3], [3,4,5], [7,8,9]])

type(data)
data
data.ndim
data.size
data.nbytes
data.shape

(3, 3)

In [ ]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
data
data.dtype

d1 = np.array([1,2,3], dtype=float)
d2 = np.array([1,2,3], dtype=complex)
d1 + d2
(d1 + d2).dtype

# w pierwiastki z liczby ujemnej
np.sqrt(np.array([-1, -2, -4], dtype=complex))

In [ ]:
cplx = np.array([3+3.j], dtype=complex)
cplx.real
cplx.imag
print(f'Ange in deg: {np.angle(cplx, deg=True)}')


In [ ]:
# Tablice utworzone na podstawie list
# i innych obiektów tablicopodobnych

s='1D'
s
data = np.array([1, 2, 3, 4])
data
data.ndim
data.shape

s='2D'
s
data = np.array([[1,2], [3,4]])
data
data.ndim
data.shape

s='3D'
s
data = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
data
data.ndim
data.shape

s='4D'
s
data = np.array([
    [
        [
            [1, 2, 3], 
            [4, 5, 6], 
            [7, 8, 9]
        ], 
        [
            [10, 11, 12], 
            [13, 14, 15], 
            [16, 17, 18]
        ],
    ],
    [ 
        [
            [19, 20, 21], 
            [22, 23, 24], 
            [25, 26, 27]
        ], 
        [
            [28, 29, 30], 
            [31, 32, 33], 
            [34, 35, 36]
        ]
    ]
])
data
data.ndim
data.shape



In [ ]:
print('Tablice wypełnione stałymi wartościami - zeros')
s = '1D'
data = np.zeros(2)
s
data
s = '2D'
data = np.zeros((2, 2))
s
data
s = '3D'
data = np.zeros((2, 2, 3))
s
data
s = '4D'
data = np.zeros((2, 2, 3, 3))
s
data

print('Tablice wypełnione stałymi wartościami - ones')
s = '1D'
data = np.ones(3)
s
data

s = '5D'
data = np.ones((2,3,4,5,6))
s
data
print(f'data.ndim: {data.ndim}')
print(f'data.shape: {data.shape}')
print(f'data.size: {data.size}')




In [ ]:
print('Wypelniania tablic')
s = 'mnozenie'
data = 5.4 * np.ones(5)
s
data

s='np.full'
data = np.full(10, 6.6)
s
data

s='np.fill'
data = np.empty(5)
data.fill(3.0)
s
data




In [ ]:
print("Tablice wypełnione rosnącymi wartościami")

s = 'generowanie tablicy z przyrostem 0.5 od 0 - 10 za pomocą arrange'
data = np.arange(0.0, 10, 0.5)
data
s

s = 'generowanie tablicy z przyrostem 0.5 od 0 - 10 za pomocą linspace'
data = np.linspace(0.0, 10, 21)
data
s

s = 'Tablice z wartościami rozmieszczonymi logarytmicznie'
data = np.logspace(0, 2, 5) # 5 punktów generowanych pomniedzy 10^0 a 10^2
s
data

s = 'inny przyklad'
data = np.logspace(0, 2, 21)
s
data

In [ ]:
print('Tablice z siatkami współrzędnych')
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

X, Y = np.meshgrid(x, y)
X
Y
Z = (X+Y)**2
Z

In [ ]:
print('Tworzenie niezainicjalizowanych tablic')
data = np.empty(3, dtype=float)
data

In [ ]:
print('Macierze')

s = 'MAciez z jedynkami na przekątnej głównej'
data = np.identity(4)
s
data


s = 'To samo co wyżej ale stworzone za pomocą f. eye'
data = np.eye(4, k=0)
s
data

s = 'k: zmiana offsetu'
data = np.eye(4, k=1)
s
data

s = 'k: zmiana offsetu'
data = np.eye(4, k=-2)
s
data

s = 'Działanie f. diag'

data = np.diag(np.arange(0, 20, 5))
s
data


In [ ]:
print('Wycinki')

data = np.arange(0, 11)
data
data[0]
data[-1]
data[1:-1]
data[1:]
data[1:-1:2]
data[-5:]

print('Tablice wielowymiarowe')
f = lambda m, n: n+10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A
A[:, 1] # druga kolumna
A[1, :] # drugi wiersz
A[:3, :3] # lewa górna ćwiartka
A[3:, :3] # lewa dolna ćwiartka
A[::2, ::2] # co drugi element począwszy od elementu [0, 0]
A[1::2, 1::3] # Elementy z co drugiego wiersza i co trzeciej kolumny począwszy od elementu [1, 1]


In [ ]:
print('Widoki')
B = A[1:5, 1:5]
A
B
B[:, :] = 0 # wycinek w orygilalnej tablicy A, przyjmie wartość 0
A
s='Aby wyeleminować taką funkcjonalnosc, należy zrobić kopię'
s
C = B[1:3, 1:3].copy()
C
C[:, :] = 1
print('C: ')
C
print('B: ')
B


In [ ]:
print('Indeksowanie logiczne i fancy indexing')

data = np.linspace(0, 1, 11)
data

s='wyodrębnianie elementów znajdujących się na 2, 4 oraz 7 popzycji'
s
data[np.array([2, 4, 7])] 

s='Ten sam efekt ale z zastosowaniem listy'
s
data[[0, 2, 7]]

print('Tablica 2D')

data = np.linspace(0, 11, 12).reshape(3, 4) # linspace(od, do, ile)
data
data[:, 2] # 2 kolumna
data[:, 1:] # wszystko oprócz kolumny 0
data[[1, 2], [1, 3]]

print('Filtrowanie zawartosci tablicy')
data
data > 7.5
data[data > 5]

print('Kolejne przyklady fancy indexing')
data = np.arange(10)
print('data: ')
data
indices = [2, 5, 7]
B = data[indices]
B
B[0] = -1  # To przypisanie nie wpływa na wartości w A
data
data[indices] = -1 # To przypisanie wpływa na wartości w A
data

In [ ]:
print('Zmiany kształtu i rozmiaru')

data = np.array([[1, 2], [3, 4]])
data
np.reshape(data, (1, 4)) # po reshape dwuwymiarowej tablicy o wymiarach 1, 4
data.reshape(4) # po reshape do 1 wymiarowego wektora

C = data.reshape(4)
C[1] = 123
data
data[0][1] = 2
data
C = data.reshape(1, 4).copy()
C

print('Funkcje ravel i flatten. Te funkcje spłaszczają tablice 2D do 1-wymiarowego wektora,\
      przy czym flatten zwraca nowa kopie tablicy')

data = np.arange(1, 5, 1).reshape(2, 2)
data
x = data.flatten()
x
data
x[0] = 123
x
data # oryginalne data

y = data.ravel()
y
y[0] = 321
y
data # zmienione dane


In [ ]:
print('Kontynuacja poprzedniego kodu, z tym, że tutaj analizUję np.newaxis oraz expand_dims')
data = np.arange(0, 5)
data

col = data[:, np.newaxis]
col

row = data[np.newaxis, :]
row

# tablica 2D
data = np.arange(1, 5, 1).reshape(2, 2)
data

B = data[:, :, np.newaxis]
B
data
B.shape

#expand_dims
data
data.shape
C = np.expand_dims(data, axis=1)
C
C.shape
D = np.expand_dims(data, axis=0)
D
D.shape



In [ ]:
print('Funkcje vstack oraz hstack')

data= np.arange(5)
data
np.vstack(data) 
np.vstack((data, data, data))

np.hstack((data, data, data)) # to nie jest oczekiwany sposób

data = data[:, np.newaxis]
data
np.hstack((data, data, data))




In [ ]:
print('Wyrażenia zwektoryzowane')

print('Operacje arytmetyczne')

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x + y
x - y
x * y
x / y

x * 2
2 ** x
y / 2
(y / 2).dtype

print('Concatenate')

a = np.array([[2, 4]])
a.shape
aa = np.concatenate([a, a], axis=0)
aa


In [ ]:
print('Funkcje działające na elementach')

a = np.linspace(-1, 1, 11)
a
y = np.sin(np.pi * a) # zaokrąglenie wyniku do 4 miejsc po przecinku
np.round(y, decimals=4)

np.add(np.sin(a)**2, np.cos(a)**2) # jedynka trygonometryczna

cos2x = np.cos(a*2)
cos2x = np.round(cos2x, decimals=6)
cos2x

cos2x_1 = np.cos(a)**2 - np.sin(a)**2
cos2x_1 = np.round(cos2x_1, decimals=6)
cos2x_1

s = f'Are equal? {np.array_equal(cos2x, cos2x_1)}'
s

def heaviside(x):
    return 1 if x > 0 else 0

heaviside(-1)
heaviside(1.5)
#heaviside(np.linspace(0, 1, 11)) # blad: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
x = np.linspace(1, 10, 11)
heaviside = np.vectorize(heaviside)
heaviside(x)

In [ ]:
print('Funkcje agregujące')
data = np.random.normal(size=(5, 5))
data

np.mean(data)
data.mean() # srednia
data.var() # wariancja
data.sum()  # suma wszystkich elementów
data.prod() # iloczyn w e
data.cumsum() # Skumulowana suma wszystkich elementów
data.cumprod() # Skumulowany iloczyn wszystkich elementów.
data.min() 
data.max()
data.all() # zwraca true jezeli wszystkie elementy sa rozne od 0
data.any() # Zwraca True, jeżeli którykolwiek z elementów tablicy ma wartość różną od zera.




In [ ]:
data = np.arange(1, 10).reshape(3, 3)
data

data.sum()
data.sum(axis=0)
data.sum(axis=1)

print('stosowanie operatorów >, <, >=, <=, == i !=')

a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b
np.all(a < b)
np.any(a < b)



In [ ]:
print('przyklad definiowania funkcji określonych odcinkowo')

def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

x = np.linspace(-5, 5, 11)
pulse(x, position=-2, height=1, width=5)
x
x >= -2
x <= 3
1 * (x >= -2)
1 * (x <= 3)

print('Ten sam przyklad ale z zastosowaniem logical_and')
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))
pulse(x, position=-2, height=1, width=5)

In [ ]:
print('Funkcja where')
# Funkcja np.where dokonuje wyboru elementów z dwóch tablic (przekazanych w drugim i trzecim argumencie) na podstawie przekazanej do niej
# tablicy wartości logicznych (tablicy warunkowej — pierwszy argument). W przypadku gdy w tablicy warunkowej na danej pozycji znajduje się True, 
# wybierane są wartości z drugiej tablicy (drugi argument), w przeciwnym razie do tablicy wynikowej trafiają elementy z trzeciej spośród tablic (trzeci argument)

x = np.linspace(-4, 4, 9)
x

x < 0
x**2
x**3
x**4
np.where(x < 0, x**2, x**3)

print('Funkcja choose')
# Wybiera wartości z listy tablic w zależności od zadanej tablicy warunkowej
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])


print('Funkcja select')
# Wybiera wartości z listy tablic w zależności od listy warunków.

np.select([x<-1, x<2, x>=2], [x**2 , x**3 , x**4])


In [ ]:
print('Operacje na zbiorach')

a = np.unique([1, 2, 3, 3]) # Zwraca nową tablicę z unikatowymi elementami, w których każda z wartości pojawia się tylko raz.
b = np.unique([2, 3, 4, 4, 5, 6, 5])
a
b

np.isin(a, b) # Sprawdza obecność elementów tablicy w innej tablicy
np.intersect1d(a, b) # czesc wspólna
np.setdiff1d(a, b) # róznica
np.setdiff1d(b, a)
np.union1d(a, b) # suma obu


In [ ]:
print('Operacja na tablicach')

data = np.arange(9).reshape(3, 3)
data
data.transpose()

data = np.random.randn(1, 2, 3, 4, 5)
data.shape
data.T.shape

data = np.arange(9).reshape(3, 3)
data
np.rot90(data)



In [14]:
print('Operacje macierzowe i wektorowe')

# mnożenie macierzy
A = np.arange(1, 7).reshape(2, 3)
A
B = np.arange(1, 7).reshape(3, 2)
B

A@B
#lub
np.dot(A, B)

AA = np.arange(9).reshape(3, 3)
AA

xx = np.arange(3)
xx
np.dot(AA, xx)

AA = np.random.rand(3, 3)
BB = np.random.rand(3, 3)
AA
BB
AA = np.asmatrix(AA)
AA
BB = np.asmatrix(BB)
BB
Ap = BB*AA*BB.I
Ap

print('Iloczyn skalarny dwóch tablic reprezentujacych wektory')
xx
np.inner(xx, xx)
# lub
np.dot(xx, xx)

yy = xx[:, np.newaxis]
yy
np.dot(yy.T, yy)


Operacje macierzowe i wektorowe


array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[22, 28],
       [49, 64]])

array([[22, 28],
       [49, 64]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([0, 1, 2])

array([ 5, 14, 23])

array([[0.76693713, 0.60465294, 0.58710009],
       [0.8668025 , 0.07995266, 0.86877649],
       [0.11651806, 0.77233814, 0.97928449]])

array([[0.12450094, 0.70808877, 0.98501462],
       [0.89945914, 0.74768684, 0.04244081],
       [0.63286524, 0.48470346, 0.82908968]])

matrix([[0.76693713, 0.60465294, 0.58710009],
        [0.8668025 , 0.07995266, 0.86877649],
        [0.11651806, 0.77233814, 0.97928449]])

matrix([[0.12450094, 0.70808877, 0.98501462],
        [0.89945914, 0.74768684, 0.04244081],
        [0.63286524, 0.48470346, 0.82908968]])

matrix([[ 0.44442582, -0.18317646,  1.47497089],
        [-0.64098181,  0.0116209 ,  2.2314717 ],
        [ 0.47208765,  0.08475369,  1.37012755]])

Iloczyn skalarny dwóch tablic reprezentujacych wektory


array([0, 1, 2])

np.int64(5)

np.int64(5)

array([[0],
       [1],
       [2]])

array([[5]])

In [ ]:
print('Iloczyn Kroneckera')
kr = np.array([1, 2, 3])
np.outer(kr, kr)

np.kron(kr, kr)

np.kron(kr[:, np.newaxis], kr[np.newaxis, :])


Iloczyn Kroneckera


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

array([1, 2, 3, 2, 4, 6, 3, 6, 9])